#!/bin/bash

INSTANCEID="$(curl http://169.254.169.254/latest/meta-data/instance-id 2>/dev/null $$ echo)"

# Create AMI
/usr/local/bin/aws ec2 describe-instances --filter Name=instance-id,Values=$INSTANCEID | grep $INSTANCEID | /usr/bin/gawk '{print $8}' |  /usr/bin/gawk -v date="$(date +"%d-%m-%Y")" '{print $1,"--name",$1,"_",date,"--no-reboot"}' | /usr/bin/gawk '{print $1,$2,$3 $4 $5,$6 $7}' | /usr/bin/xargs -L 1 /usr/local/bin/aws ec2 create-image --instance-id

# Remove AMI with more of 3 days
/usr/local/bin/aws ec2 describe-images | grep $INSTANCEID_$(date --date='3 days ago' '+%d-%m-%Y') | /usr/bin/gawk '{print $4}' | /usr/bin/xargs -L 1 /usr/local/bin/aws ec2 deregister-image --image-id

# Remove Snapshots with more of 3 days
/usr/local/bin/aws ec2 describe-snapshots | grep $INSTANCEID | /usr/bin/gawk '{print $12"_"$13}' | /usr/bin/gawk -F T '{print $1}' | grep "$(date --date='3 days ago' '+%Y-%m-%d')" | awk -F _ '{print $1}' | /usr/bin/xargs -L 1 /usr/local/bin/aws ec2 delete-snapshot --snapshot-id
